package UniStudy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DegreeCourseType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DegreeCourseType() {
    super(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x13cf5a8b21e5c3eeL, "DegreeCourseType", "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1427459160515396590");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_BACHELOR_DEGREE_0 = new EnumerationDescriptor.MemberDescriptor("BACHELOR_DEGREE", "Bachelor Degree", 0x13cf5a8b21e5c3f0L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1427459160515396592");
  private final EnumerationDescriptor.MemberDescriptor myMember_MASTER_DEGREE_0 = new EnumerationDescriptor.MemberDescriptor("MASTER_DEGREE", "Master Degree", 0x13cf5a8b21e5c3efL, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1427459160515396591");
  private final EnumerationDescriptor.MemberDescriptor myMember_POST_GRADUATE_0 = new EnumerationDescriptor.MemberDescriptor("POST_GRADUATE", "Post-graduate Course", 0x13cf5a8b21e5c3f3L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1427459160515396595");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x13cf5a8b21e5c3eeL, 0x13cf5a8b21e5c3f0L, 0x13cf5a8b21e5c3efL, 0x13cf5a8b21e5c3f3L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_BACHELOR_DEGREE_0, myMember_MASTER_DEGREE_0, myMember_POST_GRADUATE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_POST_GRADUATE_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "BACHELOR_DEGREE":
        return myMember_BACHELOR_DEGREE_0;
      case "MASTER_DEGREE":
        return myMember_MASTER_DEGREE_0;
      case "POST_GRADUATE":
        return myMember_POST_GRADUATE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
