package UniStudy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ExtraInfoType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ExtraInfoType() {
    super(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x18b564b5ef67a403L, "ExtraInfoType", "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304195");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_STRING_0 = new EnumerationDescriptor.MemberDescriptor("STRING", "string", 0x18b564b5ef67a404L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304196");
  private final EnumerationDescriptor.MemberDescriptor myMember_INTEGER_0 = new EnumerationDescriptor.MemberDescriptor("INTEGER", "integer", 0x18b564b5ef67a405L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304197");
  private final EnumerationDescriptor.MemberDescriptor myMember_FLOAT_0 = new EnumerationDescriptor.MemberDescriptor("FLOAT", "float", 0x18b564b5ef67a408L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304200");
  private final EnumerationDescriptor.MemberDescriptor myMember_DOUBLE_0 = new EnumerationDescriptor.MemberDescriptor("DOUBLE", "double", 0x18b564b5ef67a40cL, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304204");
  private final EnumerationDescriptor.MemberDescriptor myMember_BOOLEAN_0 = new EnumerationDescriptor.MemberDescriptor("BOOLEAN", "bool", 0x18b564b5ef67a411L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304209");
  private final EnumerationDescriptor.MemberDescriptor myMember_ENUMERATION_0 = new EnumerationDescriptor.MemberDescriptor("ENUMERATION", "enum", 0x18b564b5ef67a417L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/1780439960263304215");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x18b564b5ef67a403L, 0x18b564b5ef67a404L, 0x18b564b5ef67a405L, 0x18b564b5ef67a408L, 0x18b564b5ef67a40cL, 0x18b564b5ef67a411L, 0x18b564b5ef67a417L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_STRING_0, myMember_INTEGER_0, myMember_FLOAT_0, myMember_DOUBLE_0, myMember_BOOLEAN_0, myMember_ENUMERATION_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_STRING_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "STRING":
        return myMember_STRING_0;
      case "INTEGER":
        return myMember_INTEGER_0;
      case "FLOAT":
        return myMember_FLOAT_0;
      case "DOUBLE":
        return myMember_DOUBLE_0;
      case "BOOLEAN":
        return myMember_BOOLEAN_0;
      case "ENUMERATION":
        return myMember_ENUMERATION_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
