package UniStudy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PostGraduateLevel extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PostGraduateLevel() {
    super(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d051L, "PostGraduateLevel", "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/8662004459809132625");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_FIRST_0 = new EnumerationDescriptor.MemberDescriptor("FIRST", "FIRST", 0x78359f29b5c5d052L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/8662004459809132626");
  private final EnumerationDescriptor.MemberDescriptor myMember_SECOND_0 = new EnumerationDescriptor.MemberDescriptor("SECOND", "SECOND", 0x78359f29b5c5d054L, "r:3cf796c9-a780-4278-b34f-67670fa92009(UniStudy.structure)/8662004459809132628");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d051L, 0x78359f29b5c5d052L, 0x78359f29b5c5d054L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_FIRST_0, myMember_SECOND_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_FIRST_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "FIRST":
        return myMember_FIRST_0;
      case "SECOND":
        return myMember_SECOND_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
