package UniStudy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CareerManagement_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<!DOCTYPE html>");
    tgs.newLine();
    tgs.append("<html>");
    tgs.newLine();
    tgs.append("<head>");
    tgs.newLine();
    tgs.append("<title>Our Domain docs</title>");
    tgs.newLine();
    tgs.append("</head>");
    tgs.newLine();
    tgs.append("<body>");
    tgs.newLine();
    tgs.append("<h1>Universities</h1>");
    tgs.newLine();
    tgs.increaseIndent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.universities$MlEO)) {
      tgs.appendNode(item);
    }
    tgs.decreaseIndent();
    tgs.append("</body>");
    tgs.newLine();
    tgs.append("</html>");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink universities$MlEO = MetaAdapterFactory.getContainmentLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x3b69734a0801c738L, 0x3b69734a08021c56L, "universities");
  }
}
