package UniStudy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ExtraInfo_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.higher_multiplicity$aHLY) > 1) {
      tgs.indent();
      tgs.append("<li>");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL) + ": ");
      tgs.newLine();
      tgs.indent();
      tgs.append("<ul>");
      tgs.newLine();
      tgs.increaseIndent();
      String[] arr = SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.value$7X7d).split(",");
      for (String value : arr) {
        tgs.indent();
        tgs.append("<li>");
        tgs.append(value);
        tgs.append("</li>");
        tgs.newLine();
      }
      tgs.decreaseIndent();
      tgs.indent();
      tgs.append("</ul>");
      tgs.newLine();
      tgs.indent();
      tgs.append("</li>");
      tgs.newLine();

    } else {
      tgs.indent();
      tgs.append("<li>");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL) + ": ");
      tgs.append("</li>");
      tgs.newLine();
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$7X7d = MetaAdapterFactory.getProperty(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x18b564b5ef67a3fbL, 0x18b564b5ef67a3feL, "value");
    /*package*/ static final SProperty higher_multiplicity$aHLY = MetaAdapterFactory.getProperty(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x18b564b5ef67a3fbL, 0x18b564b5ef67a425L, "higher_multiplicity");
  }
}
