package UniStudy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Thesis_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<h3>Thesis #" + (SNodeOperations.getIndexInParent(ctx.getPrimaryInput()) + 1) + ": ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append("</h3>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<ul>");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("<li>Thesis type: ");
    tgs.append("" + SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$o$qe));
    tgs.append("</li>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<li>Student: ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.student$oGBL), PROPS.name$MnvL));
    tgs.append("</li>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<li>Supervisor: ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.supervisor$oHkO), PROPS.name$MnvL));
    tgs.append("</li>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<li>Referenced degree course: ");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.degree_course$9CaM));
    tgs.append("</li>");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("</ul>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty type$o$qe = MetaAdapterFactory.getProperty(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d00cL, 0x78359f29b5c5d010L, "type");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink student$oGBL = MetaAdapterFactory.getReferenceLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d00cL, 0x78359f29b5c5d01eL, "student");
    /*package*/ static final SReferenceLink supervisor$oHkO = MetaAdapterFactory.getReferenceLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d00cL, 0x78359f29b5c5d021L, "supervisor");
    /*package*/ static final SReferenceLink degree_course$9CaM = MetaAdapterFactory.getReferenceLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d00cL, 0x13cf5a8b21e5c426L, "degree_course");
  }
}
