package UniStudy.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Objects;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class DegreeCourseReference_Constraints extends BaseConstraintsDescriptor {
  public DegreeCourseReference_Constraints() {
    super(CONCEPTS.DegreeCourseReference$8I);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.degree_course$vJLQ, this, false, true) {
      @Override
      public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
        return true;
      }
      @Override
      public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
        if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(referenceNode), CONCEPTS.Student$Dd)) {
          ListSequence.fromList(SLinkOperations.getChildren(newReferentNode, LINKS.enrolled_students$cHU3)).addElement(SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x13cf5a8b21e5c413L, "UniStudy.structure.StudentReference")));
          SLinkOperations.setTarget(ListSequence.fromList(SLinkOperations.getChildren(newReferentNode, LINKS.enrolled_students$cHU3)).last(), LINKS.student$_OLQ, SNodeOperations.cast(SNodeOperations.getParent(referenceNode), CONCEPTS.Student$Dd));
          if ((oldReferentNode != null)) {
            ListSequence.fromList(SLinkOperations.getChildren(oldReferentNode, LINKS.enrolled_students$cHU3)).removeWhere((it) -> Objects.equals(SLinkOperations.getTarget(it, LINKS.student$_OLQ), SNodeOperations.getParent(referenceNode)));
          }
        }
        SLinkOperations.setTarget(referenceNode, LINKS.degree_course$vJLQ, newReferentNode);
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DegreeCourseReference$8I = MetaAdapterFactory.getConcept(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d0d2L, "UniStudy.structure.DegreeCourseReference");
    /*package*/ static final SConcept Student$Dd = MetaAdapterFactory.getConcept(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5cfe1L, "UniStudy.structure.Student");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink degree_course$vJLQ = MetaAdapterFactory.getReferenceLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d0d2L, 0x78359f29b5c5d0d3L, "degree_course");
    /*package*/ static final SContainmentLink enrolled_students$cHU3 = MetaAdapterFactory.getContainmentLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d024L, 0x13cf5a8b21e5c465L, "enrolled_students");
    /*package*/ static final SReferenceLink student$_OLQ = MetaAdapterFactory.getReferenceLink(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x13cf5a8b21e5c413L, 0x13cf5a8b21e5c414L, "student");
  }
}
