package UniStudy.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Department_Constraints extends BaseConstraintsDescriptor {
  public Department_Constraints() {
    super(CONCEPTS.Department$Ce);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Department$Ce = MetaAdapterFactory.getConcept(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d064L, "UniStudy.structure.Department");
  }
}
