package UniStudy.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Master_Constraints extends BaseConstraintsDescriptor {
  public Master_Constraints() {
    super(CONCEPTS.Master$W9);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Master$W9 = MetaAdapterFactory.getConcept(0x6d0cfce3b6ce4188L, 0xa63493977a58376fL, 0x78359f29b5c5d048L, "UniStudy.structure.Master");
  }
}
